#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding         34

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

bspc rule -a Firefox desktop='^2'

$HOME/.config/polybar/launch.sh &

feh --bg-scale ~/Pictures/Wallpapers/wallpaper.png &

xsetroot -cursor_name left_ptr &

picom --menu-opacity=1 --fade-delta=0 --shadow-opacity=0 &
